# Generated by Django 5.2.17 on 2026-09-19 11:54

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20, unique=True)),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('channel', models.CharField(blank=True, max_length=300)),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('message', models.TextField()),
                ('sources', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='summarizer.chatsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=10)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('full_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='summarizer.video')),
            ],
        ),
        migrations.AddField(
            model_name='chatsession',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='summarizer.video'),
        ),
        migrations.CreateModel(
            name='TranscriptChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.PositiveIntegerField()),
                ('start', models.FloatField()),
                ('end', models.FloatField()),
                ('text', models.TextField()),
                ('word_count', models.PositiveIntegerField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='summarizer.video')),
            ],
            options={
                'ordering': ['video', 'chunk_id'],
                'constraints': [models.UniqueConstraint(fields=('video', 'chunk_id'), name='unique_chunk_per_video')],
            },
        ),
    ]
