# Generated by Django 5.2.17 on 2026-09-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='summary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
