# Generated by Django 5.2.17 on 2026-09-20 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0002_video_summary_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('start', models.FloatField()),
                ('end', models.FloatField()),
                ('source_segment_index', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='summarizer.video')),
            ],
            options={
                'ordering': ['video', 'start'],
            },
        ),
    ]
